name: Deploy to GitHub Pages

on:
  push:
    branches: develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build react application

    env:
      REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
      REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}

    steps:
    - uses: actions/checkout@v2
    - name: UseNode.js 21
      uses: actions/setup-node@v1
      with:
        node-version: 21
    - run: npm ci
    - run: CI=false npm run build --if-present
    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
